version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: myorganizer
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
